# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push:
    branches:
      - main
      - develop
      - 'releases/**'
  pull_request:
    branches:
      - main
# env:
#   DATABASE_TEST_URL: postgres://postgres:postgres@postgres:5432/action-db
#   DATABASE_URL: postgres://postgres:postgres@postgres:5432/action-db
#   EMAIL_ADDRESS: "test@test.com"
#   EMAIL_PASSWORD: "test"

jobs:
  deploy:

    runs-on: ubuntu-latest

    # services:
    #   postgres:
    #     image: postgres
    #     env:
    #       POSTGRES_DB: action-db
    #       POSTGRES_PASSWORD: postgres
    #     ports:
    #       - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install -r requirements.txt
    - name: Pytest 
      run: pytest ./
